version: '3.8'

services:
  ground_station:
    image: gs_backend
    container_name: ground_station
    build:
      context: ./
      dockerfile: ground_station.dockerfile
    ports:
      - 80:80
    #environment:
    #  RX_PORT: ${RX_PORT?Variable not set}
    #  TX_PORT: ${TX_PORT?Variable not set}
    #  RADIO_PORT: ${RADIO_PORT?Variable not set}
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
      - "/dev/ttyUSB2:/dev/ttyUSB2"
    volume:
      - .:/ground_station
    command: tail -F anything

  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - 6379:6379
    environment:
        - ALLOW_EMPTY_PASSWORD=yes

